package org.company.app.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

//generated by https://m3.material.io/theme-builder#/custom
//Color palette was taken here: https://colorhunt.co/palettes/popular

val darkPalette = FamousColors(
    primaryBackground = Color(0xFF141217),
    primaryText = Color.White,
    secondaryBackground = Color(0xFF302938),
    secondaryText = Color.White,
    tintColor = Color(0xFFAB9EB8),
    dividerColor = Color(0xFF473D54)
)

object FamousTheme {
    val colors: FamousColors
        @Composable
        get() = LocalFamousColor.current
}

val LocalFamousColor = staticCompositionLocalOf<FamousColors> { error("No default implementation for colors") }